# Generated by Django 3.2 on 2021-07-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_court', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='sheff',
            field=models.CharField(default='Manish', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
