# Generated by Django 3.2 on 2021-07-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_court', '0003_auto_20210715_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='sheff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food_court.sheff'),
        ),
    ]
