# Generated by Django 3.2 on 2021-07-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_court', '0005_auto_20210716_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adress Enteries'},
        ),
        migrations.AddField(
            model_name='food',
            name='origin_city',
            field=models.ManyToManyField(to='food_court.City'),
        ),
    ]
